postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: eden
  password:
  min_messages: WARNING

development:
  <<: *postgresql
  database: likemarks_development

test:
  <<: *postgresql
  database: likemarks_test

production:
  <<: *postgresql
  database: likemarks_development
